### ISSUE TITLE
Firefox : scroll conflict between color picker and page scroll on mobile

### ISSUE THREAD

**Issue by bjlaa** [deebov/atomik-color-picker#2]
Hi,

Very much appreciate finding this library, which is truly 100% accessible and it's not an easy thing to find 😄 

I noted an issue with scrolling on mobile, which seems to happen only on Firefox : the page scroll sometimes overtakes the color picker dragging, and then both the page scrolling and the color picker value get both affected by moving the thumb on the screen. Here's a capture of it (in the second part, our previous implementation, that doesn't seem to present the same issue).

https://user-images.githubusercontent.com/12382534/205665363-d223d145-a196-4872-b78d-8f3e81521b83.mp4

This is a minor issue, which doesn't prevent us from using the lib but we would still appreciate if we could find a fix for it. Can lend a hand if needed !

**Comment by deebov** [comment]
Hey @bjlaa, thanks for reporting the report. I'm really glad that you're considering using this library.

I will take a look at the problem over the weekend.

**Comment by deebov** [comment]
@bjlaa I pushed a new path update. Could you please try the latest version and see if the issue still persists? 
I tested using iOS Safari and Firefox. The issue is gone.

**Comment by bjlaa** [comment]
@deebov Works like a charm ! Thank you for your quickness ! :)
